new Frase(ID: 0,
          Texto: "...",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 1 }),
new Frase(ID: 1,
          Texto: "¿No vas a decir nada?",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 2 }),
new Frase(ID: 2,
          Texto: "¿Qué te voy a decir si estoy todo el rato conmigo?",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 3 }),
new Frase(ID: 3,
          Texto: "No sé, un hola que tal...",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 4 }),
new Frase(ID: 4,
          Texto: "¿Eres penosillo eh?",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 5 }),
new Frase(ID: 5,
          Texto: "Si ya me conoces, me gusta tener un poquito de atención.",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 6 }),
new Frase(ID: 6,
          Texto: "Sólo respira y mira el mar... Es precioso...",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 7 }),
new Frase(ID: 7,
          Texto: "...",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 8 }),
new Frase(ID: 8,
          Texto: "...",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 9 }),
new Frase(ID: 9,
          Texto: "La verdad es que si...",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 10 }),
new Frase(ID: 10,
          Texto: "[Pausa para contemplar.]",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 11 }),
new Frase(ID: 11,
          Texto: "La verdad es que es impresionante... Se respira mucha calma...",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 12 }),
new Frase(ID: 12,
          Texto: "¿Recuerdas que esto antes era imposible? Simplemente estar aquí, observando sin nada más que hacer. Estando.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 13 }),
new Frase(ID: 13,
          Texto: "Si... El psicólogo ayudó mucho la verdad jajaja.",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 14 }),
new Frase(ID: 14,
          Texto: "Ya ves...",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 15 }),
new Frase(ID: 15,
          Texto: "¿Cómo fue que llegamos a estar en paz?",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 16 }),
new Frase(ID: 16,
          Texto: "Me sorprende que me lo preguntes tú, siempre eres el que intenta romperla.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 17 }),
new Frase(ID: 17,
          Texto: "Quizá por eso se me ha olvidado.",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 18 }),
new Frase(ID: 18,
          Texto: "A ver... Al principio de los tiempos había mucha ansiedad...",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 19 }),
new Frase(ID: 19,
          Texto: "Tampoco hace falta que te pongas así.",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 20 }),
new Frase(ID: 20,
          Texto: "Jeje, vale vale... ¿Recuerdas cuando empezamos con la ansiedad? Sin poder respirar, siempre pensando, pensando pensando... Como tener una nube de preocupaciones irreales en la cabeza que te impiden actuar con naturalidad ni espontaneidad.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 21 }),
new Frase(ID: 21,
          Texto: "Sí... Eso sí lo recuerdo. Recuerdo no ser capaz de decirte nada bueno, sólo que todo iba a salir mal, que hicieras cosas aunque no quisieras, que todo iba a salir mal...",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 22 }),
new Frase(ID: 22,
          Texto: "Fueron unos años largos si... ¿Y qué paso después?",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 23 }),
new Frase(ID: 23,
          Texto: "Mmm, que empezamos con el primer psicólogo.",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 24 }),
new Frase(ID: 24,
          Texto: "Exacto, Juan nos ayudó mucho a entender porqué decías las cosas que decías y cómo funcionabas vamos.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 25 }),
new Frase(ID: 25,
          Texto: "Sí... Es verdad que muchas veces digo cosas sin pensar. Antes te agobiaban mucho.",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 26 }),
new Frase(ID: 26,
          Texto: "¿Y después?",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 27 }),
new Frase(ID: 27,
          Texto: "Pues... Estuvimos un tiempo mejor, pero había algo que no terminaba de encajar dentro de nosotros, no nos entendíamos y nos hacíamos daño.",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 28 }),
new Frase(ID: 28,
          Texto: "Y por eso fuimos a la segunda psicóloga, que nos ayudó más a entender como nos sentíamos el uno con el otro e incluso de donde venían algunos comportamientos del presente.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 29 }),
new Frase(ID: 29,
          Texto: "Es verdad, y ahí fue cuando me diste el ultimatum.",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 30 }),
new Frase(ID: 30,
          Texto: "Eso es. No podía dejar que me siguieras hablando tan mal.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 31 }),
new Frase(ID: 31,
          Texto: "Es verdad... No me enorgullezco de cómo te hablaba...",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 32 }),
new Frase(ID: 32,
          Texto: "...",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 33 }),
new Frase(ID: 33,
          Texto: "... Y... ¿Cómo era eso que me decías? ¿Háblame como quien?",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 34 }),
new Frase(ID: 34,
          Texto: "Como mi mejor amigo.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 35 }),
new Frase(ID: 35,
          Texto: "¿Y porqué lo hiciste?",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 36 }),
new Frase(ID: 36,
          Texto: "Pues la verdad... No lo sé. No sé si lo leí en algún sitio o qué, pero recuerdo perfectamente el momento.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 37 }),
new Frase(ID: 37,
          Texto: "Yo también, nos estábamos duchando y dijiste muy serio: \"Se acabó, acabo de pasarlo fatal y no puedo soportar que me sigas hablando así. Ten compasión de mí y háblame como si fuera Juanma.\"",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 38 }),
new Frase(ID: 38,
          Texto: "Es verdad, me puse muy serio, lo había olvidado. Pero funcionó.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 39 }),
new Frase(ID: 39,
          Texto: "Sí, la verdad es que sí...",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 40 }),
new Frase(ID: 40,
          Texto: "Aunque me tienes que reconocer que tuve que ser muy pesado para hacerte cambiar.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 41 }),
new Frase(ID: 41,
          Texto: "Pues... Sí, jeje, lo siento.",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 42 }),
new Frase(ID: 42,
          Texto: "Está bien, así pude forjar una actitud más fuerte conmigo y el resto del mundo para que no me pisotearan.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 43 }),
new Frase(ID: 43,
          Texto: "Todo camino andado es camino eh.",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 44 }),
new Frase(ID: 44,
          Texto: "Si...",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 45 }),
new Frase(ID: 45,
          Texto: "[Pausa para contemplar.]",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 46 }),
new Frase(ID: 46,
          Texto: "[Pausa para contemplar.]",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 47 }),
new Frase(ID: 47,
          Texto: "Espera, pero ahí no acaba la cosa.",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 48 }),
new Frase(ID: 48,
          Texto: "Es verdad, esperaba que te acordaras.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 49 }),
new Frase(ID: 49,
          Texto: "Claro que me acuerdo, después de eso te hablaba mucho mejor, pero seguía siendo un papagayo.",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 50 }),
new Frase(ID: 50,
          Texto: "Jajajaja, efectivamente, un papagayo.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 51 }),
new Frase(ID: 51,
          Texto: "Es que me gusta mucho hablar.",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 52 }),
new Frase(ID: 52,
          Texto: "Lo sé, pero también es necesario respirar y estar en calma.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 53 }),
new Frase(ID: 53,
          Texto: "Sí... Ahí la meditación ayudó mucho. ¿Porqué empezaste?",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 54 }),
new Frase(ID: 54,
          Texto: "Pues porque decían que era bueno para la mente.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 55 }),
new Frase(ID: 55,
          Texto: "Ya jope, ¿pero no hubo nada más?",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 56 }),
new Frase(ID: 56,
          Texto: "Mmm, bueno, también porque me parecía guay no te voy a engañar.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 57 }),
new Frase(ID: 57,
          Texto: "¿Y ya está? ¿No era porque apareció alguien especial?",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 58 }),
new Frase(ID: 58,
          Texto: "Pues ahí te equivocas, empezamos antes de conocerla.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 59 }),
new Frase(ID: 59,
          Texto: "¿Sí? ¿Pero...? ¡Ah! Es verdad, que antes en vez de dejar pasar lo que te decía, me dabas bola jajaja",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 60 }),
new Frase(ID: 60,
          Texto: "Si jajaja",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 61 }),
new Frase(ID: 61,
          Texto: "[Ambos ríen]",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 62 }),
new Frase(ID: 62,
          Texto: "[Ambos ríen]",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 63 }),
new Frase(ID: 63,
          Texto: "Si si, ahora recuerdo que fue ella la que te dijo que la estabas cagando jajaja.",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 64 }),
new Frase(ID: 64,
          Texto: "Y cuanta razón tenía... También me dijo que yo no era mi mente, que eso si que fue fuerte...",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 65 }),
new Frase(ID: 65,
          Texto: "Ya... De eso si me acuerdo muy bien. Te hizo ver que todo lo que yo decía no era real.",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 66 }),
new Frase(ID: 66,
          Texto: "Pues si... Y me costó eh, te tenía como la verdad absoluta. A lo mejor por eso me pude crear una compasión tan fuerte.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 67 }),
new Frase(ID: 67,
          Texto: "Es posible, hiciste un buen trabajo.",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 68 }),
new Frase(ID: 68,
          Texto: "Gracias, me costó.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 69 }),
new Frase(ID: 69,
          Texto: "Lo sé.",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 70 }),
new Frase(ID: 70,
          Texto: "[Pausa para contemplar.]",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 71 }),
new Frase(ID: 71,
          Texto: "¿Y no te gustaría no haber pasado todo lo malo que pasamos? Los ataques de ansiedad no fueron bonitos...",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 72 }),
new Frase(ID: 72,
          Texto: "No lo fueron, no... Pero aun así, estoy orgulloso y contento de haberlo pasado.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 73 }),
new Frase(ID: 73,
          Texto: "Suenas muy teatral, como si lo hubieras escrito.",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 74 }),
new Frase(ID: 74,
          Texto: "¿Quién te dice que no lo he hecho?",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 75 }),
new Frase(ID: 75,
          Texto: "Ya ya, no cambies de tema.",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 76 }),
new Frase(ID: 76,
          Texto: "Bueno vale, te explico. Todos esos momentos se perderán en el tiempo... Como un pedo en el viento...",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 77 }),
new Frase(ID: 77,
          Texto: "Jajajaja, ahí me has pillado",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 78 }),
new Frase(ID: 78,
          Texto: "[Ambos ríen]",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 79 }),
new Frase(ID: 79,
          Texto: "[Ambos ríen]",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 80 }),
new Frase(ID: 80,
          Texto: "[Pausa para contemplar.]",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 81 }),
new Frase(ID: 81,
          Texto: "[Pausa para contemplar.]",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 82 }),
new Frase(ID: 82,
          Texto: "Pues, no me arrepiento no. Siento que eso me ayudó a evolucionar hasta el punto donde estoy hoy.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 83 }),
new Frase(ID: 83,
          Texto: "Sí bueno, eso está muy bonito, pero hemos tenido la vida muy sencilla.",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 84 }),
new Frase(ID: 84,
          Texto: "Eso tampoco te lo voy a negar, me siento muy afortunado y privilegiado con lo que me ha dado la vida. La familia que tengo es maravillosa y eso ni lo pude ni lo puedo cambiar.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 85 }),
new Frase(ID: 85,
          Texto: "¿Entonces?",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 86 }),
new Frase(ID: 86,
          Texto: "Pues que la familia que hemos tenido es una cosa y a dónde hemos querido llegar con nuestra situación vital es otra.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 87 }),
new Frase(ID: 87,
          Texto: "Explícate.",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 88 }),
new Frase(ID: 88,
          Texto: "A ver, cuando lo estuvimos pasando tan mal, no veía un momento en el que fuera a estar bien. Yo acepté que la vida iba a ser así, con ansiedad crónica, siempre en mi mente e incapaz de ser feliz. Pero antes de empezar con la segunda psicóloga, me pregunté: ¿Porqué tengo tanta ansiedad? Y fue por ello que fuí con ella, porque con la Gestalt sentía que podía conocerme mejor, saber de dónde venía mi ansiedad, porqué lo era en el presente y cómo podía estar mejor. Y por ello también fuimos luego al tercer psicólogo que también era Gestalt. El decidir ir a terapia, enfrentarte a tus mierdas mas internas, a tu oscuridad, tu sombra, tus traumas... Es un camino duro que decidí tomar para estar mejor, sabiendo que iba a doler... Porque podría haber enterrado todo eso en lo más profundo de mi ser, tener ataques de ansiedad de vez en cuando, seguir inquieto y demás... Pero decidí estar mejor.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 89 }),
new Frase(ID: 89,
          Texto: "Pero decirlo así suena como muy facil. Suena a como \"¿ESTAS MAL? NO ESTES MAL.\"",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 90 }),
new Frase(ID: 90,
          Texto: "Tienes razón, voy a intentar decirlo con otras palabras dame un segundo.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 91 }),
new Frase(ID: 91,
          Texto: "[Pausa para contemplar.]",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 92 }),
new Frase(ID: 92,
          Texto: "[Pausa para contemplar.]",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 93 }),
new Frase(ID: 93,
          Texto: "¿Lo tienes?",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 94 }),
new Frase(ID: 94,
          Texto: "Lo tengo.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 95 }),
new Frase(ID: 95,
          Texto: "Dale.",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 96 }),
new Frase(ID: 96,
          Texto: "[Sonido de pedo]",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 97 }),
new Frase(ID: 97,
          Texto: "Pfff jajajaja. Ya van dos bromas de pedos.",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 98 }),
new Frase(ID: 98,
          Texto: "No me pude resistir, necesito rebajar tensión.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 99 }),
new Frase(ID: 99,
          Texto: "[Pausa para contemplar.]",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 100 }),
new Frase(ID: 100,
          Texto: "Vale, lo tengo. Cuando una persona está muy mal y le dices \"No estés mal\" o \"No tengas ansiedad\" es de ser un gilipollas.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 101 }),
new Frase(ID: 101,
          Texto: "En efecto.",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 102 }),
new Frase(ID: 102,
          Texto: "Pero realmente no hay otra forma.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 103 }),
new Frase(ID: 103,
          Texto: "Eres un gilipollas.",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 104 }),
new Frase(ID: 104,
          Texto: "A ver, déjame explicarme. Cuando una persona tiene depresión, ansiedad muy muy fuerte o estados similares eso no sirve. La persona necesita de atención psiquiátrica y psicológica y no hay más que hablar. Pero una vez que no está en esos umbrales, si la persona quiere esatr mejor tiene que hacer un compromiso fuerte con ella misma para hacerlo ¿Y sabes cuál es una parte muy importante de todo esto?",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 105 }),
new Frase(ID: 105,
          Texto: "La confianza. Que se me hayan olvidado algunas cosas no significa que no estemos juntos siempre, no me hagas más preguntas retóricas.",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 106 }),
new Frase(ID: 106,
          Texto: "Vaaale vale. Pues eso, la confianza, tanto en tí mismo a la hora de hacer el proceso, como en la vida.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 107 }),
new Frase(ID: 107,
          Texto: "En la vida... También suena muy místico.",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 108 }),
new Frase(ID: 108,
          Texto: "Ya, pero es que no hay otra forma.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 109 }),
new Frase(ID: 109,
          Texto: "Bueno, pero te olvidas también del ego. Tener bajito el ego es importante.",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 110 }),
new Frase(ID: 110,
          Texto: "Sí, la verdad es que sí.",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 111 }),
new Frase(ID: 111,
          Texto: "Si tu y yo no nos hubiéramos bajado unos tonitos, no habríamos podido alcanzar la calma. Confiar está genial, pero asumir que eres humano, que cometes errores, que te has hecho mucho daño, que estás sufriendo y que es posible que tengas algo de culpa... Pues es muy duro también.",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 112 }),
new Frase(ID: 112,
          Texto: "Eso tampoco gusta no...",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 113 }),
new Frase(ID: 113,
          Texto: "[Pausa para contemplar.]",
          Interlocutor: InterlocutorEnum.TuMismo,
          Mostrar: true,
          SiguienteFrase: new int[1] { 114 }),
new Frase(ID: 114,
          Texto: "[Pausa para contemplar.]",
          Interlocutor: InterlocutorEnum.Jugador,
          Mostrar: true,
          SiguienteFrase: new int[1] { 115 })