//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Controles/ControlesJugador.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControlesJugador: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControlesJugador()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControlesJugador"",
    ""maps"": [
        {
            ""name"": ""Andando"",
            ""id"": ""eab7c0c6-20f7-4a12-85a3-4418ed3f181a"",
            ""actions"": [
                {
                    ""name"": ""Derecha"",
                    ""type"": ""Button"",
                    ""id"": ""7ad08ffb-6349-4846-a25e-6034f42d7768"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Izquierda"",
                    ""type"": ""Button"",
                    ""id"": ""8ad8ee38-f79c-48dd-9fab-7921cb53c599"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Accion"",
                    ""type"": ""Button"",
                    ""id"": ""d149581b-c7dd-4bb3-9159-2e1dca6623c0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3567832d-3a9d-4789-880d-42545b3128ac"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Derecha"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d839a0a-647c-4c11-9d11-e7afb7123665"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Derecha"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ee5398b0-38cb-4359-a5b7-90971cad3fd9"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Derecha"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5630e04-cd07-4dad-9e4e-472441d7094a"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Derecha"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7914ff49-3090-4c1d-ba7c-1054ffa703ef"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Izquierda"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""efe1dbc6-cab8-40cd-ab7f-562d56cc7769"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Izquierda"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""633ada58-a996-40ba-9bb0-e67b03a5b7ee"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Izquierda"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b43aa3e-571f-4922-b027-580523c8bf43"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Izquierda"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""af341879-50c2-4350-950f-82ad06fc973b"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9fcc76a9-b250-435c-8add-81d380adabec"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Conversando"",
            ""id"": ""b3abf97a-c005-441d-a144-d777fb9c268b"",
            ""actions"": [
                {
                    ""name"": ""Continuar"",
                    ""type"": ""Button"",
                    ""id"": ""31aa6852-a504-4229-b002-b7dfbb548ac1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Arriba"",
                    ""type"": ""Button"",
                    ""id"": ""e01135ae-3da4-4862-a67c-3c1a3b94bc40"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Abajo"",
                    ""type"": ""Button"",
                    ""id"": ""5a189cdb-f635-4b12-8015-39dae4c954fa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8c724b4b-4d5d-4647-b5f9-750ec601bb1c"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Continuar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fbdbacac-cf8f-43b1-ad85-5d0ba4b8d8c2"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Continuar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4d86481-502e-4b23-87f2-d72d8f2706cf"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Arriba"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5405740c-bb8f-4c95-984c-84bb2587450e"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Arriba"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""63226dcf-0e7c-446f-b3f3-6755466770bc"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Arriba"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f5b09f2-350a-486c-9d37-3d4055eaceef"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Arriba"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e04c2ec8-7332-466a-81d5-66ecbac00640"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Abajo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86839f1b-5d70-4745-8ca4-8cd41786dcd5"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Abajo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f54ca5d3-a354-4048-b631-856186069f41"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Abajo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8df4adb3-0268-4188-99f2-adf16694ec40"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Abajo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Meditando"",
            ""id"": ""f497169e-2805-45f8-99c9-00b676160297"",
            ""actions"": [
                {
                    ""name"": ""Respirar"",
                    ""type"": ""Button"",
                    ""id"": ""35dc5f93-43fb-4c55-8233-6478e52f93cf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Salir"",
                    ""type"": ""Button"",
                    ""id"": ""c33f4df4-3d5d-41ae-bc11-553798e06ca5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""758ea99b-d895-4d19-8adb-e59bc402424a"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Salir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""565958ab-98c8-49a1-8b90-16c9c843e11e"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Respirar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0360cbde-95c9-432e-8552-fc227a1ef3d0"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Respirar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Inicio"",
            ""id"": ""927783ee-d4e6-4ae4-9d75-ecf4ae662a8d"",
            ""actions"": [
                {
                    ""name"": ""Accion"",
                    ""type"": ""Button"",
                    ""id"": ""d2887918-4201-4c84-9246-26e7eb6bb8ea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""17d9e0c6-22b6-4ec3-a2f4-6451c2f90fec"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78a8b46d-003a-4e18-a7db-86b430585c0f"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Eligiendo"",
            ""id"": ""e289ed3d-dbd2-4b7d-85d0-ab2e689a45c4"",
            ""actions"": [
                {
                    ""name"": ""Puntero"",
                    ""type"": ""PassThrough"",
                    ""id"": ""39a432f5-9bd2-4f2d-840a-b75993ee0dca"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Navegar"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ca49938b-7862-4f42-8196-c9bd344443ac"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Presionar"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b3f3348f-8529-4268-81c5-63af117eeba0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Arriba"",
                    ""type"": ""Button"",
                    ""id"": ""a1387af2-f75c-4a42-8bad-65e2352ab041"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Abajo"",
                    ""type"": ""Button"",
                    ""id"": ""21ef03b7-73d3-43ca-bf6f-ccbf8a1342ab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fdf48d2c-6784-4349-9734-16a9ba7fb118"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Presionar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ea26bcb-49f4-4b6e-93a2-eafdd4bcc1af"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Presionar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""678f62d0-8a4e-4d30-a314-2534dee3e568"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Presionar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""6c5325ae-b02e-462b-b3fe-abbce6076e81"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navegar"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""43dc184b-00c5-4c2a-a089-5adbb5b7fccf"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navegar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b36fa963-6ab2-4944-a0d1-d964cf731b0c"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navegar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""55fba437-af0d-421b-a160-7d576bf3d3f9"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navegar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""8c827f74-c40e-4b3c-8fe7-d2e9663884a3"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navegar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""60550fe3-0a1d-41a5-9ce8-ad5f589969a9"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navegar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9425b8ca-5bd2-4d39-bf2a-a85ca94adbaf"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navegar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""2ccf1d34-4838-4cc9-a39e-8546f9c6d72e"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navegar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4ab9af9b-7707-432d-8315-4cef5f8a3dee"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navegar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""917d052c-d15e-453f-aff2-114610f40fa0"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navegar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Joystick"",
                    ""id"": ""b85e1fc8-cf43-48ea-bc52-ff80d50e1eb1"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navegar"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e50966b4-1a3f-4922-bda8-e2bc262a1031"",
                    ""path"": ""<Joystick>/stick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navegar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f0e41a9e-ed15-405b-8175-b6716c425bcd"",
                    ""path"": ""<Joystick>/stick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navegar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""eb69415f-791f-4ad4-aef8-d29d29e5b8ae"",
                    ""path"": ""<Joystick>/stick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navegar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7a2fbfc9-3c0c-4c20-9a68-8a5388c9f947"",
                    ""path"": ""<Joystick>/stick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navegar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""ea8bdbc8-6e0d-4770-bc9c-6049cf3701df"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navegar"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e1975812-1b86-4466-b680-601a9be25609"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navegar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7b4e49e2-4805-47a2-92dc-aedb88ec77d2"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navegar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""90fafb40-50e2-4a1b-81fb-34ea33874fb7"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navegar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""6eca5320-b69e-443e-a022-2c42d1980743"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navegar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1bd90042-0466-4d26-a5cd-e0ae01d08ea2"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navegar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9c49a270-6d61-4f2d-ab28-20016cd5e5b7"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navegar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""aa867498-0ac5-4f31-a544-972f2e1606e5"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navegar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""32ecaf10-14c4-446c-a747-3be3c6866d04"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navegar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9419fc32-735b-4b13-a5e1-54e9d3e5ac04"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Puntero"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7dd7bf1e-efff-448a-bf27-d42bf3ae430f"",
                    ""path"": ""<Pen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Puntero"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b14a75e9-2cd7-467c-8c30-16b0dbc4176b"",
                    ""path"": ""<Touchscreen>/touch*/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Puntero"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ffa797c-f8f7-43da-91fc-742904a4dabf"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Arriba"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a6d0df6-c498-49f7-a37b-82535ac7254d"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Arriba"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84f6762d-2df3-4d0a-9571-187cf0aa5dfa"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Arriba"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80741a41-d70c-44c9-a32d-d0e6ca6ca8c2"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Arriba"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5dc981c7-e326-45d0-aff3-2af13ffc04cb"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Abajo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7863a2b2-4358-49a9-9dfc-dd6e8b09a125"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Abajo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30354b44-6b67-4091-8ba2-71246d7bc6da"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Abajo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""89da18a9-9d75-4f6c-8e50-ee1661d34b3f"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Abajo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""903ba538-56f4-4752-aedf-ad01529cbbf1"",
            ""actions"": [
                {
                    ""name"": ""Navigate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""7e8a9e2b-5c2e-4068-a31e-f6158873a027"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""eed68c16-f82b-4308-ac30-f848193380c4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""9bbe3402-ad5f-41f7-920d-cf0a8ded25cf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Point"",
                    ""type"": ""PassThrough"",
                    ""id"": ""62c2ed9e-46dd-481b-9f57-17d6a884cb73"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""PassThrough"",
                    ""id"": ""8cdfda83-7a0b-4067-8b38-13c49bdc2163"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ScrollWheel"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5f6beab0-e354-4874-9a03-5c973b196a3d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MiddleClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""78633241-48e6-4afd-b25f-f9a879e193c9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""16dee036-f083-47cd-aab4-ba6d66f13805"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrackedDevicePosition"",
                    ""type"": ""PassThrough"",
                    ""id"": ""83fbb321-81b4-46c3-8b57-eceec214a978"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrackedDeviceOrientation"",
                    ""type"": ""PassThrough"",
                    ""id"": ""4215fb45-fe34-4b98-8d62-3906c8dd6ea2"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""cbfb6e90-336c-4171-a561-c229146e817b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""de29103e-a9d7-4981-946a-e719efb42d0d"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a3a1b01c-733b-4759-be3e-4c4e5a99ba0d"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5884950f-95f9-4307-a25f-bd5438ce451f"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e2ff5759-5ab9-4b83-a4c7-469b9eb99514"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""357979cc-034c-4ec0-bca1-b7e2454edc60"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""31cf869b-cd3e-4334-a3af-19a1027b8ea2"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9cc1a29a-114e-43d9-9733-79dd34b8625e"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5bc1d646-6e55-4810-a3e6-2a2180f99bf1"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b5aa069e-acdf-43a5-9ee0-7694557c49f0"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Joystick"",
                    ""id"": ""ed8485c0-c8bb-47ff-8a0e-50cad49ab7c3"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7b5aca7c-bb6b-42b0-973b-bf5846bd458d"",
                    ""path"": ""<Joystick>/stick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""52cde9de-d9c4-46e0-b515-5c025fe70d6b"",
                    ""path"": ""<Joystick>/stick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""69080934-9671-4fdc-9485-7445c9f49bc2"",
                    ""path"": ""<Joystick>/stick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c81bbf02-5ff2-48fa-b6b5-f3c649d72f6f"",
                    ""path"": ""<Joystick>/stick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""6bd1f6eb-1852-4dd1-8083-64eee251a86a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9e4841ee-fce4-4b04-9ff1-2749d89c0b66"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2174288f-86a2-45a8-8d76-60d0db683418"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""94ea1305-f2c4-4624-beb9-3ee04712c4de"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3fa8907f-087e-4586-907b-d218118a2c14"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d4c4d86f-cb43-498c-8f9a-95717d5e939d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""19bb1cc1-5a7a-4646-b847-94267f5b8f89"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""682a2bcd-0921-4ecc-a6c5-49ae085ab99c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b7dcff0f-a868-40c7-a726-927bb2910d2d"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""bc1b5882-7a9f-4b44-871a-f0f4a3b52744"",
                    ""path"": ""*/{Submit}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Gamepad;Touch;Joystick;XR"",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f0c0e24-a9e7-4080-a118-759239a161e0"",
                    ""path"": ""*/{Cancel}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse;Gamepad;Touch;Joystick;XR"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""613a4791-41f4-42bc-b12a-be1bd9202032"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf98b7dc-69a7-4a61-94e7-931687af31f9"",
                    ""path"": ""<Pen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""69c3cdb5-9711-4d3e-abf0-d7a036cb69c9"",
                    ""path"": ""<Touchscreen>/touch*/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touch"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""03d73db1-8069-484f-b63e-a44e67e1bd08"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9674e6f1-49d2-4e8e-9a23-f9387a9a1f15"",
                    ""path"": ""<Pen>/tip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a7c64830-3447-4894-9554-84cc86ce7faa"",
                    ""path"": ""<Touchscreen>/touch*/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touch"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""58b1aeb1-7e85-4f2e-981d-2790a2eb5383"",
                    ""path"": ""<XRController>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f5849deb-ab09-431f-a7f2-2dc187649115"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""ScrollWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b3eb049a-86f6-4c38-b93a-4627d4c66868"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""MiddleClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8744085d-51a4-40e9-ab55-abb70be5e568"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f0962f3-fbdb-4fea-8f7a-fb9f3bfcffd9"",
                    ""path"": ""<XRController>/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""TrackedDevicePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1eebdb79-2ef7-4caf-9f66-183fd7a47102"",
                    ""path"": ""<XRController>/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""TrackedDeviceOrientation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Andando
        m_Andando = asset.FindActionMap("Andando", throwIfNotFound: true);
        m_Andando_Derecha = m_Andando.FindAction("Derecha", throwIfNotFound: true);
        m_Andando_Izquierda = m_Andando.FindAction("Izquierda", throwIfNotFound: true);
        m_Andando_Accion = m_Andando.FindAction("Accion", throwIfNotFound: true);
        // Conversando
        m_Conversando = asset.FindActionMap("Conversando", throwIfNotFound: true);
        m_Conversando_Continuar = m_Conversando.FindAction("Continuar", throwIfNotFound: true);
        m_Conversando_Arriba = m_Conversando.FindAction("Arriba", throwIfNotFound: true);
        m_Conversando_Abajo = m_Conversando.FindAction("Abajo", throwIfNotFound: true);
        // Meditando
        m_Meditando = asset.FindActionMap("Meditando", throwIfNotFound: true);
        m_Meditando_Respirar = m_Meditando.FindAction("Respirar", throwIfNotFound: true);
        m_Meditando_Salir = m_Meditando.FindAction("Salir", throwIfNotFound: true);
        // Inicio
        m_Inicio = asset.FindActionMap("Inicio", throwIfNotFound: true);
        m_Inicio_Accion = m_Inicio.FindAction("Accion", throwIfNotFound: true);
        // Eligiendo
        m_Eligiendo = asset.FindActionMap("Eligiendo", throwIfNotFound: true);
        m_Eligiendo_Puntero = m_Eligiendo.FindAction("Puntero", throwIfNotFound: true);
        m_Eligiendo_Navegar = m_Eligiendo.FindAction("Navegar", throwIfNotFound: true);
        m_Eligiendo_Presionar = m_Eligiendo.FindAction("Presionar", throwIfNotFound: true);
        m_Eligiendo_Arriba = m_Eligiendo.FindAction("Arriba", throwIfNotFound: true);
        m_Eligiendo_Abajo = m_Eligiendo.FindAction("Abajo", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Navigate = m_UI.FindAction("Navigate", throwIfNotFound: true);
        m_UI_Submit = m_UI.FindAction("Submit", throwIfNotFound: true);
        m_UI_Cancel = m_UI.FindAction("Cancel", throwIfNotFound: true);
        m_UI_Point = m_UI.FindAction("Point", throwIfNotFound: true);
        m_UI_Click = m_UI.FindAction("Click", throwIfNotFound: true);
        m_UI_ScrollWheel = m_UI.FindAction("ScrollWheel", throwIfNotFound: true);
        m_UI_MiddleClick = m_UI.FindAction("MiddleClick", throwIfNotFound: true);
        m_UI_RightClick = m_UI.FindAction("RightClick", throwIfNotFound: true);
        m_UI_TrackedDevicePosition = m_UI.FindAction("TrackedDevicePosition", throwIfNotFound: true);
        m_UI_TrackedDeviceOrientation = m_UI.FindAction("TrackedDeviceOrientation", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Andando
    private readonly InputActionMap m_Andando;
    private List<IAndandoActions> m_AndandoActionsCallbackInterfaces = new List<IAndandoActions>();
    private readonly InputAction m_Andando_Derecha;
    private readonly InputAction m_Andando_Izquierda;
    private readonly InputAction m_Andando_Accion;
    public struct AndandoActions
    {
        private @ControlesJugador m_Wrapper;
        public AndandoActions(@ControlesJugador wrapper) { m_Wrapper = wrapper; }
        public InputAction @Derecha => m_Wrapper.m_Andando_Derecha;
        public InputAction @Izquierda => m_Wrapper.m_Andando_Izquierda;
        public InputAction @Accion => m_Wrapper.m_Andando_Accion;
        public InputActionMap Get() { return m_Wrapper.m_Andando; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AndandoActions set) { return set.Get(); }
        public void AddCallbacks(IAndandoActions instance)
        {
            if (instance == null || m_Wrapper.m_AndandoActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_AndandoActionsCallbackInterfaces.Add(instance);
            @Derecha.started += instance.OnDerecha;
            @Derecha.performed += instance.OnDerecha;
            @Derecha.canceled += instance.OnDerecha;
            @Izquierda.started += instance.OnIzquierda;
            @Izquierda.performed += instance.OnIzquierda;
            @Izquierda.canceled += instance.OnIzquierda;
            @Accion.started += instance.OnAccion;
            @Accion.performed += instance.OnAccion;
            @Accion.canceled += instance.OnAccion;
        }

        private void UnregisterCallbacks(IAndandoActions instance)
        {
            @Derecha.started -= instance.OnDerecha;
            @Derecha.performed -= instance.OnDerecha;
            @Derecha.canceled -= instance.OnDerecha;
            @Izquierda.started -= instance.OnIzquierda;
            @Izquierda.performed -= instance.OnIzquierda;
            @Izquierda.canceled -= instance.OnIzquierda;
            @Accion.started -= instance.OnAccion;
            @Accion.performed -= instance.OnAccion;
            @Accion.canceled -= instance.OnAccion;
        }

        public void RemoveCallbacks(IAndandoActions instance)
        {
            if (m_Wrapper.m_AndandoActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IAndandoActions instance)
        {
            foreach (var item in m_Wrapper.m_AndandoActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_AndandoActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public AndandoActions @Andando => new AndandoActions(this);

    // Conversando
    private readonly InputActionMap m_Conversando;
    private List<IConversandoActions> m_ConversandoActionsCallbackInterfaces = new List<IConversandoActions>();
    private readonly InputAction m_Conversando_Continuar;
    private readonly InputAction m_Conversando_Arriba;
    private readonly InputAction m_Conversando_Abajo;
    public struct ConversandoActions
    {
        private @ControlesJugador m_Wrapper;
        public ConversandoActions(@ControlesJugador wrapper) { m_Wrapper = wrapper; }
        public InputAction @Continuar => m_Wrapper.m_Conversando_Continuar;
        public InputAction @Arriba => m_Wrapper.m_Conversando_Arriba;
        public InputAction @Abajo => m_Wrapper.m_Conversando_Abajo;
        public InputActionMap Get() { return m_Wrapper.m_Conversando; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ConversandoActions set) { return set.Get(); }
        public void AddCallbacks(IConversandoActions instance)
        {
            if (instance == null || m_Wrapper.m_ConversandoActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ConversandoActionsCallbackInterfaces.Add(instance);
            @Continuar.started += instance.OnContinuar;
            @Continuar.performed += instance.OnContinuar;
            @Continuar.canceled += instance.OnContinuar;
            @Arriba.started += instance.OnArriba;
            @Arriba.performed += instance.OnArriba;
            @Arriba.canceled += instance.OnArriba;
            @Abajo.started += instance.OnAbajo;
            @Abajo.performed += instance.OnAbajo;
            @Abajo.canceled += instance.OnAbajo;
        }

        private void UnregisterCallbacks(IConversandoActions instance)
        {
            @Continuar.started -= instance.OnContinuar;
            @Continuar.performed -= instance.OnContinuar;
            @Continuar.canceled -= instance.OnContinuar;
            @Arriba.started -= instance.OnArriba;
            @Arriba.performed -= instance.OnArriba;
            @Arriba.canceled -= instance.OnArriba;
            @Abajo.started -= instance.OnAbajo;
            @Abajo.performed -= instance.OnAbajo;
            @Abajo.canceled -= instance.OnAbajo;
        }

        public void RemoveCallbacks(IConversandoActions instance)
        {
            if (m_Wrapper.m_ConversandoActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IConversandoActions instance)
        {
            foreach (var item in m_Wrapper.m_ConversandoActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ConversandoActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ConversandoActions @Conversando => new ConversandoActions(this);

    // Meditando
    private readonly InputActionMap m_Meditando;
    private List<IMeditandoActions> m_MeditandoActionsCallbackInterfaces = new List<IMeditandoActions>();
    private readonly InputAction m_Meditando_Respirar;
    private readonly InputAction m_Meditando_Salir;
    public struct MeditandoActions
    {
        private @ControlesJugador m_Wrapper;
        public MeditandoActions(@ControlesJugador wrapper) { m_Wrapper = wrapper; }
        public InputAction @Respirar => m_Wrapper.m_Meditando_Respirar;
        public InputAction @Salir => m_Wrapper.m_Meditando_Salir;
        public InputActionMap Get() { return m_Wrapper.m_Meditando; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MeditandoActions set) { return set.Get(); }
        public void AddCallbacks(IMeditandoActions instance)
        {
            if (instance == null || m_Wrapper.m_MeditandoActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MeditandoActionsCallbackInterfaces.Add(instance);
            @Respirar.started += instance.OnRespirar;
            @Respirar.performed += instance.OnRespirar;
            @Respirar.canceled += instance.OnRespirar;
            @Salir.started += instance.OnSalir;
            @Salir.performed += instance.OnSalir;
            @Salir.canceled += instance.OnSalir;
        }

        private void UnregisterCallbacks(IMeditandoActions instance)
        {
            @Respirar.started -= instance.OnRespirar;
            @Respirar.performed -= instance.OnRespirar;
            @Respirar.canceled -= instance.OnRespirar;
            @Salir.started -= instance.OnSalir;
            @Salir.performed -= instance.OnSalir;
            @Salir.canceled -= instance.OnSalir;
        }

        public void RemoveCallbacks(IMeditandoActions instance)
        {
            if (m_Wrapper.m_MeditandoActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMeditandoActions instance)
        {
            foreach (var item in m_Wrapper.m_MeditandoActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MeditandoActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MeditandoActions @Meditando => new MeditandoActions(this);

    // Inicio
    private readonly InputActionMap m_Inicio;
    private List<IInicioActions> m_InicioActionsCallbackInterfaces = new List<IInicioActions>();
    private readonly InputAction m_Inicio_Accion;
    public struct InicioActions
    {
        private @ControlesJugador m_Wrapper;
        public InicioActions(@ControlesJugador wrapper) { m_Wrapper = wrapper; }
        public InputAction @Accion => m_Wrapper.m_Inicio_Accion;
        public InputActionMap Get() { return m_Wrapper.m_Inicio; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InicioActions set) { return set.Get(); }
        public void AddCallbacks(IInicioActions instance)
        {
            if (instance == null || m_Wrapper.m_InicioActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InicioActionsCallbackInterfaces.Add(instance);
            @Accion.started += instance.OnAccion;
            @Accion.performed += instance.OnAccion;
            @Accion.canceled += instance.OnAccion;
        }

        private void UnregisterCallbacks(IInicioActions instance)
        {
            @Accion.started -= instance.OnAccion;
            @Accion.performed -= instance.OnAccion;
            @Accion.canceled -= instance.OnAccion;
        }

        public void RemoveCallbacks(IInicioActions instance)
        {
            if (m_Wrapper.m_InicioActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInicioActions instance)
        {
            foreach (var item in m_Wrapper.m_InicioActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InicioActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InicioActions @Inicio => new InicioActions(this);

    // Eligiendo
    private readonly InputActionMap m_Eligiendo;
    private List<IEligiendoActions> m_EligiendoActionsCallbackInterfaces = new List<IEligiendoActions>();
    private readonly InputAction m_Eligiendo_Puntero;
    private readonly InputAction m_Eligiendo_Navegar;
    private readonly InputAction m_Eligiendo_Presionar;
    private readonly InputAction m_Eligiendo_Arriba;
    private readonly InputAction m_Eligiendo_Abajo;
    public struct EligiendoActions
    {
        private @ControlesJugador m_Wrapper;
        public EligiendoActions(@ControlesJugador wrapper) { m_Wrapper = wrapper; }
        public InputAction @Puntero => m_Wrapper.m_Eligiendo_Puntero;
        public InputAction @Navegar => m_Wrapper.m_Eligiendo_Navegar;
        public InputAction @Presionar => m_Wrapper.m_Eligiendo_Presionar;
        public InputAction @Arriba => m_Wrapper.m_Eligiendo_Arriba;
        public InputAction @Abajo => m_Wrapper.m_Eligiendo_Abajo;
        public InputActionMap Get() { return m_Wrapper.m_Eligiendo; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(EligiendoActions set) { return set.Get(); }
        public void AddCallbacks(IEligiendoActions instance)
        {
            if (instance == null || m_Wrapper.m_EligiendoActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_EligiendoActionsCallbackInterfaces.Add(instance);
            @Puntero.started += instance.OnPuntero;
            @Puntero.performed += instance.OnPuntero;
            @Puntero.canceled += instance.OnPuntero;
            @Navegar.started += instance.OnNavegar;
            @Navegar.performed += instance.OnNavegar;
            @Navegar.canceled += instance.OnNavegar;
            @Presionar.started += instance.OnPresionar;
            @Presionar.performed += instance.OnPresionar;
            @Presionar.canceled += instance.OnPresionar;
            @Arriba.started += instance.OnArriba;
            @Arriba.performed += instance.OnArriba;
            @Arriba.canceled += instance.OnArriba;
            @Abajo.started += instance.OnAbajo;
            @Abajo.performed += instance.OnAbajo;
            @Abajo.canceled += instance.OnAbajo;
        }

        private void UnregisterCallbacks(IEligiendoActions instance)
        {
            @Puntero.started -= instance.OnPuntero;
            @Puntero.performed -= instance.OnPuntero;
            @Puntero.canceled -= instance.OnPuntero;
            @Navegar.started -= instance.OnNavegar;
            @Navegar.performed -= instance.OnNavegar;
            @Navegar.canceled -= instance.OnNavegar;
            @Presionar.started -= instance.OnPresionar;
            @Presionar.performed -= instance.OnPresionar;
            @Presionar.canceled -= instance.OnPresionar;
            @Arriba.started -= instance.OnArriba;
            @Arriba.performed -= instance.OnArriba;
            @Arriba.canceled -= instance.OnArriba;
            @Abajo.started -= instance.OnAbajo;
            @Abajo.performed -= instance.OnAbajo;
            @Abajo.canceled -= instance.OnAbajo;
        }

        public void RemoveCallbacks(IEligiendoActions instance)
        {
            if (m_Wrapper.m_EligiendoActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IEligiendoActions instance)
        {
            foreach (var item in m_Wrapper.m_EligiendoActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_EligiendoActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public EligiendoActions @Eligiendo => new EligiendoActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
    private readonly InputAction m_UI_Navigate;
    private readonly InputAction m_UI_Submit;
    private readonly InputAction m_UI_Cancel;
    private readonly InputAction m_UI_Point;
    private readonly InputAction m_UI_Click;
    private readonly InputAction m_UI_ScrollWheel;
    private readonly InputAction m_UI_MiddleClick;
    private readonly InputAction m_UI_RightClick;
    private readonly InputAction m_UI_TrackedDevicePosition;
    private readonly InputAction m_UI_TrackedDeviceOrientation;
    public struct UIActions
    {
        private @ControlesJugador m_Wrapper;
        public UIActions(@ControlesJugador wrapper) { m_Wrapper = wrapper; }
        public InputAction @Navigate => m_Wrapper.m_UI_Navigate;
        public InputAction @Submit => m_Wrapper.m_UI_Submit;
        public InputAction @Cancel => m_Wrapper.m_UI_Cancel;
        public InputAction @Point => m_Wrapper.m_UI_Point;
        public InputAction @Click => m_Wrapper.m_UI_Click;
        public InputAction @ScrollWheel => m_Wrapper.m_UI_ScrollWheel;
        public InputAction @MiddleClick => m_Wrapper.m_UI_MiddleClick;
        public InputAction @RightClick => m_Wrapper.m_UI_RightClick;
        public InputAction @TrackedDevicePosition => m_Wrapper.m_UI_TrackedDevicePosition;
        public InputAction @TrackedDeviceOrientation => m_Wrapper.m_UI_TrackedDeviceOrientation;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void AddCallbacks(IUIActions instance)
        {
            if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
            @Navigate.started += instance.OnNavigate;
            @Navigate.performed += instance.OnNavigate;
            @Navigate.canceled += instance.OnNavigate;
            @Submit.started += instance.OnSubmit;
            @Submit.performed += instance.OnSubmit;
            @Submit.canceled += instance.OnSubmit;
            @Cancel.started += instance.OnCancel;
            @Cancel.performed += instance.OnCancel;
            @Cancel.canceled += instance.OnCancel;
            @Point.started += instance.OnPoint;
            @Point.performed += instance.OnPoint;
            @Point.canceled += instance.OnPoint;
            @Click.started += instance.OnClick;
            @Click.performed += instance.OnClick;
            @Click.canceled += instance.OnClick;
            @ScrollWheel.started += instance.OnScrollWheel;
            @ScrollWheel.performed += instance.OnScrollWheel;
            @ScrollWheel.canceled += instance.OnScrollWheel;
            @MiddleClick.started += instance.OnMiddleClick;
            @MiddleClick.performed += instance.OnMiddleClick;
            @MiddleClick.canceled += instance.OnMiddleClick;
            @RightClick.started += instance.OnRightClick;
            @RightClick.performed += instance.OnRightClick;
            @RightClick.canceled += instance.OnRightClick;
            @TrackedDevicePosition.started += instance.OnTrackedDevicePosition;
            @TrackedDevicePosition.performed += instance.OnTrackedDevicePosition;
            @TrackedDevicePosition.canceled += instance.OnTrackedDevicePosition;
            @TrackedDeviceOrientation.started += instance.OnTrackedDeviceOrientation;
            @TrackedDeviceOrientation.performed += instance.OnTrackedDeviceOrientation;
            @TrackedDeviceOrientation.canceled += instance.OnTrackedDeviceOrientation;
        }

        private void UnregisterCallbacks(IUIActions instance)
        {
            @Navigate.started -= instance.OnNavigate;
            @Navigate.performed -= instance.OnNavigate;
            @Navigate.canceled -= instance.OnNavigate;
            @Submit.started -= instance.OnSubmit;
            @Submit.performed -= instance.OnSubmit;
            @Submit.canceled -= instance.OnSubmit;
            @Cancel.started -= instance.OnCancel;
            @Cancel.performed -= instance.OnCancel;
            @Cancel.canceled -= instance.OnCancel;
            @Point.started -= instance.OnPoint;
            @Point.performed -= instance.OnPoint;
            @Point.canceled -= instance.OnPoint;
            @Click.started -= instance.OnClick;
            @Click.performed -= instance.OnClick;
            @Click.canceled -= instance.OnClick;
            @ScrollWheel.started -= instance.OnScrollWheel;
            @ScrollWheel.performed -= instance.OnScrollWheel;
            @ScrollWheel.canceled -= instance.OnScrollWheel;
            @MiddleClick.started -= instance.OnMiddleClick;
            @MiddleClick.performed -= instance.OnMiddleClick;
            @MiddleClick.canceled -= instance.OnMiddleClick;
            @RightClick.started -= instance.OnRightClick;
            @RightClick.performed -= instance.OnRightClick;
            @RightClick.canceled -= instance.OnRightClick;
            @TrackedDevicePosition.started -= instance.OnTrackedDevicePosition;
            @TrackedDevicePosition.performed -= instance.OnTrackedDevicePosition;
            @TrackedDevicePosition.canceled -= instance.OnTrackedDevicePosition;
            @TrackedDeviceOrientation.started -= instance.OnTrackedDeviceOrientation;
            @TrackedDeviceOrientation.performed -= instance.OnTrackedDeviceOrientation;
            @TrackedDeviceOrientation.canceled -= instance.OnTrackedDeviceOrientation;
        }

        public void RemoveCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUIActions instance)
        {
            foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UIActions @UI => new UIActions(this);
    public interface IAndandoActions
    {
        void OnDerecha(InputAction.CallbackContext context);
        void OnIzquierda(InputAction.CallbackContext context);
        void OnAccion(InputAction.CallbackContext context);
    }
    public interface IConversandoActions
    {
        void OnContinuar(InputAction.CallbackContext context);
        void OnArriba(InputAction.CallbackContext context);
        void OnAbajo(InputAction.CallbackContext context);
    }
    public interface IMeditandoActions
    {
        void OnRespirar(InputAction.CallbackContext context);
        void OnSalir(InputAction.CallbackContext context);
    }
    public interface IInicioActions
    {
        void OnAccion(InputAction.CallbackContext context);
    }
    public interface IEligiendoActions
    {
        void OnPuntero(InputAction.CallbackContext context);
        void OnNavegar(InputAction.CallbackContext context);
        void OnPresionar(InputAction.CallbackContext context);
        void OnArriba(InputAction.CallbackContext context);
        void OnAbajo(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnNavigate(InputAction.CallbackContext context);
        void OnSubmit(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnPoint(InputAction.CallbackContext context);
        void OnClick(InputAction.CallbackContext context);
        void OnScrollWheel(InputAction.CallbackContext context);
        void OnMiddleClick(InputAction.CallbackContext context);
        void OnRightClick(InputAction.CallbackContext context);
        void OnTrackedDevicePosition(InputAction.CallbackContext context);
        void OnTrackedDeviceOrientation(InputAction.CallbackContext context);
    }
}
